// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQi7bZVG0fmjlwGa3tjdLjiYw6NPtKbs',
    appId: '1:48453550473:web:747293d05eac3253e76158',
    messagingSenderId: '48453550473',
    projectId: 'ceppark-4e4bb',
    authDomain: 'ceppark-4e4bb.firebaseapp.com',
    storageBucket: 'ceppark-4e4bb.firebasestorage.app',
    measurementId: 'G-5GV6ZTLCR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS5nTs4EeYhZLfbZigZ8-x8Oo92YMQrOM',
    appId: '1:48453550473:android:93ed8ac0e5e100e9e76158',
    messagingSenderId: '48453550473',
    projectId: 'ceppark-4e4bb',
    storageBucket: 'ceppark-4e4bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-hBzN9r7XLVLWCjgdTzm5Erdevbw-Vsc',
    appId: '1:48453550473:ios:479100a2482f0950e76158',
    messagingSenderId: '48453550473',
    projectId: 'ceppark-4e4bb',
    storageBucket: 'ceppark-4e4bb.firebasestorage.app',
    iosBundleId: 'com.example.ceppark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-hBzN9r7XLVLWCjgdTzm5Erdevbw-Vsc',
    appId: '1:48453550473:ios:479100a2482f0950e76158',
    messagingSenderId: '48453550473',
    projectId: 'ceppark-4e4bb',
    storageBucket: 'ceppark-4e4bb.firebasestorage.app',
    iosBundleId: 'com.example.ceppark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJQi7bZVG0fmjlwGa3tjdLjiYw6NPtKbs',
    appId: '1:48453550473:web:3376506c31dc46bde76158',
    messagingSenderId: '48453550473',
    projectId: 'ceppark-4e4bb',
    authDomain: 'ceppark-4e4bb.firebaseapp.com',
    storageBucket: 'ceppark-4e4bb.firebasestorage.app',
    measurementId: 'G-HL2JYR4N20',
  );
}
